// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct VaultClientProgram;

impl VaultClientProgram {
    pub const ROUTE_ID_VAULT: u8 = 1;
    pub const ROUTE_ID_ADMIN: u8 = 2;
}

impl sails_rs::client::Program for VaultClientProgram {}

pub trait VaultClient {
    type Env: sails_rs::client::GearEnv;
    fn vault(&self) -> sails_rs::client::Service<vault::VaultImpl, Self::Env>;
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> VaultClient for sails_rs::client::Actor<VaultClientProgram, E> {
    type Env = E;
    fn vault(&self) -> sails_rs::client::Service<vault::VaultImpl, Self::Env> {
        self.service(VaultClientProgram::ROUTE_ID_VAULT)
    }
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env> {
        self.service(VaultClientProgram::ROUTE_ID_ADMIN)
    }
}
pub trait VaultClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(self) -> sails_rs::client::PendingCtor<VaultClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> VaultClientCtors
    for sails_rs::client::Deployment<VaultClientProgram, E>
{
    type Env = E;
    fn create(self) -> sails_rs::client::PendingCtor<VaultClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> (), 0);
}

pub mod vault {
    use super::*;

    pub trait Vault {
        type Env: sails_rs::client::GearEnv;
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        /// #[payable]
        fn deposit(&mut self) -> sails_rs::client::PendingCall<io::Deposit, Self::Env>;
        fn total_balance(&self) -> sails_rs::client::PendingCall<io::TotalBalance, Self::Env>;
        /// #[returns_value]
        fn withdraw(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env>;
    }

    pub struct VaultImpl;

    impl sails_rs::client::Identifiable for VaultImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([165, 156, 4, 221, 46, 84, 41, 108]);
    }

    impl<E: sails_rs::client::GearEnv> Vault for sails_rs::client::Service<VaultImpl, E> {
        type Env = E;
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((account,))
        }
        fn deposit(&mut self) -> sails_rs::client::PendingCall<io::Deposit, Self::Env> {
            self.pending_call(())
        }
        fn total_balance(&self) -> sails_rs::client::PendingCall<io::TotalBalance, Self::Env> {
            self.pending_call(())
        }
        fn withdraw(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env> {
            self.pending_call((amount,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(BalanceOf (account: ActorId) -> u128 | String, 0, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Deposit () -> u128 | String, 1, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TotalBalance () -> u128 | String, 2, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Withdraw (amount: u128) -> () | String, 3, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode, ReflectHash)]
        #[codec(crate = sails_rs::scale_codec)]
        #[reflect_hash(crate = sails_rs)]
        pub enum VaultEvents {
            #[codec(index = 0)]
            Deposited([u8; 32], u128, u128),
            #[codec(index = 1)]
            Withdrawn([u8; 32], u128, u128),
        }

        impl VaultEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Deposited { .. } => 0,
                    Self::Withdrawn { .. } => 1,
                }
            }
        }

        impl sails_rs::client::Event for VaultEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for VaultEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for VaultImpl {
            type Event = VaultEvents;
        }
    }
}

pub mod admin {
    use super::*;

    pub trait Admin {
        type Env: sails_rs::client::GearEnv;
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env>;
        fn owner(&self) -> sails_rs::client::PendingCall<io::Owner, Self::Env>;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env>;
    }

    pub struct AdminImpl;

    impl sails_rs::client::Identifiable for AdminImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([51, 63, 45, 8, 176, 121, 118, 65]);
    }

    impl<E: sails_rs::client::GearEnv> Admin for sails_rs::client::Service<AdminImpl, E> {
        type Env = E;
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env> {
            self.pending_call(())
        }
        fn owner(&self) -> sails_rs::client::PendingCall<io::Owner, Self::Env> {
            self.pending_call(())
        }
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(IsPaused () -> bool | String, 0, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Owner () -> ActorId | String, 1, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Pause () -> () | String, 2, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Unpause () -> () | String, 3, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode, ReflectHash)]
        #[codec(crate = sails_rs::scale_codec)]
        #[reflect_hash(crate = sails_rs)]
        pub enum AdminEvents {
            #[codec(index = 0)]
            Paused([u8; 32]),
            #[codec(index = 1)]
            Unpaused([u8; 32]),
        }

        impl AdminEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Paused { .. } => 0,
                    Self::Unpaused { .. } => 1,
                }
            }
        }

        impl sails_rs::client::Event for AdminEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for AdminEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for AdminImpl {
            type Event = AdminEvents;
        }
    }
}
